/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* `httpResource` is still an experimental feature - NOT PRODUCTION READY
* Generated Angular service for CalendareResource
* Do not edit this file manually
*/
import { HttpContext, HttpContextToken, HttpHeaders, HttpParams, httpResource, HttpResourceOptions, HttpResourceRef, HttpResourceRequest } from "@angular/common/http";
import { inject, Injectable, Signal } from "@angular/core";
import { BASE_PATH_CALENDAREAPI, CLIENT_CONTEXT_TOKEN_CALENDAREAPI } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { FeatureResponse, PrincipalResponse, CredentialResponse, UsrCredentialType, CredentialSecretResponse, PermissionResponse, PrivilegeResponse, MembershipDirection, MembershipResponse, GroupMemberRef, RelationshipTypes, CollectionResponse, CalendarScheduleItem, AddressbookItem, MailboxItem } from "../models";

@Injectable({ providedIn: "root" })
export class CalendareResource {
    private readonly basePath: string = inject(BASE_PATH_CALENDAREAPI);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_CALENDAREAPI;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'CalendareApi');
    }

    getVersion(resourceOptions: HttpResourceOptions<FeatureResponse, unknown> & { defaultValue: NoInfer<FeatureResponse> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<FeatureResponse>;
    getVersion(resourceOptions?: HttpResourceOptions<FeatureResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<FeatureResponse | undefined>;
    /** Get version and features by calender client information */
    getVersion(resourceOptions?: HttpResourceOptions<FeatureResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<FeatureResponse | undefined> {
        return httpResource(() => {
            return {
                url: `${this.basePath}/api/version`,
                method: "GET",
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    ping(resourceOptions: HttpResourceOptions<any, unknown> & { defaultValue: NoInfer<any> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<any>;
    ping(resourceOptions?: HttpResourceOptions<any, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<any | undefined>;
    ping(resourceOptions?: HttpResourceOptions<any, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<any | undefined> {
        return httpResource(() => {
            return {
                url: `${this.basePath}/api/site/ping`,
                method: "GET",
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    getUserList(types: Signal<Array<string>> | Array<string>, search: Signal<string | undefined> | string | undefined, unrestricted: Signal<boolean | undefined> | boolean | undefined, technical: Signal<boolean | undefined> | boolean | undefined, resourceOptions: HttpResourceOptions<Array<PrincipalResponse>, unknown> & { defaultValue: NoInfer<Array<PrincipalResponse>> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<PrincipalResponse>>;
    getUserList(types: Signal<Array<string>> | Array<string>, search?: Signal<string | undefined> | string, unrestricted?: Signal<boolean | undefined> | boolean, technical?: Signal<boolean | undefined> | boolean, resourceOptions?: HttpResourceOptions<Array<PrincipalResponse>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<PrincipalResponse> | undefined>;
    /** Returns visible principals */
    getUserList(types: Signal<Array<string>> | Array<string>, search?: Signal<string | undefined> | string, unrestricted?: Signal<boolean | undefined> | boolean, technical?: Signal<boolean | undefined> | boolean, resourceOptions?: HttpResourceOptions<Array<PrincipalResponse>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<PrincipalResponse> | undefined> {
        return httpResource(() => {
            let params = new HttpParams();
            const searchValue = typeof search === 'function' ? search() : search;
            if (searchValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, searchValue, 'search');
            }
            const typesValue = typeof types === 'function' ? types() : types;
            if (typesValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, typesValue, 'types');
            }
            const unrestrictedValue = typeof unrestricted === 'function' ? unrestricted() : unrestricted;
            if (unrestrictedValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, unrestrictedValue, 'unrestricted');
            }
            const technicalValue = typeof technical === 'function' ? technical() : technical;
            if (technicalValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, technicalValue, 'technical');
            }
            return {
                url: `${this.basePath}/api/user`,
                method: "GET",
                params,
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    getUser(username: Signal<string> | string, resourceOptions: HttpResourceOptions<PrincipalResponse, unknown> & { defaultValue: NoInfer<PrincipalResponse> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<PrincipalResponse>;
    getUser(username: Signal<string> | string, resourceOptions?: HttpResourceOptions<PrincipalResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<PrincipalResponse | undefined>;
    /** Returns principal */
    getUser(username: Signal<string> | string, resourceOptions?: HttpResourceOptions<PrincipalResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<PrincipalResponse | undefined> {
        return httpResource(() => {
            return {
                url: `${this.basePath}/api/user/${typeof username === 'function' ? username() : username}`,
                method: "GET",
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    getPrincipalOfMyself(resourceOptions: HttpResourceOptions<PrincipalResponse, unknown> & { defaultValue: NoInfer<PrincipalResponse> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<PrincipalResponse>;
    getPrincipalOfMyself(resourceOptions?: HttpResourceOptions<PrincipalResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<PrincipalResponse | undefined>;
    /** Returns current user's basic infos */
    getPrincipalOfMyself(resourceOptions?: HttpResourceOptions<PrincipalResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<PrincipalResponse | undefined> {
        return httpResource(() => {
            return {
                url: `${this.basePath}/api/credentials`,
                method: "GET",
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    getCredentialsOfUser(username: Signal<string> | string, resourceOptions: HttpResourceOptions<Array<CredentialResponse>, unknown> & { defaultValue: NoInfer<Array<CredentialResponse>> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<CredentialResponse>>;
    getCredentialsOfUser(username: Signal<string> | string, resourceOptions?: HttpResourceOptions<Array<CredentialResponse>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<CredentialResponse> | undefined>;
    /** Returns credential entries */
    getCredentialsOfUser(username: Signal<string> | string, resourceOptions?: HttpResourceOptions<Array<CredentialResponse>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<CredentialResponse> | undefined> {
        return httpResource(() => {
            return {
                url: `${this.basePath}/api/credentials/user/${typeof username === 'function' ? username() : username}`,
                method: "GET",
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    getCredentialTypes(resourceOptions: HttpResourceOptions<Array<UsrCredentialType>, unknown> & { defaultValue: NoInfer<Array<UsrCredentialType>> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<UsrCredentialType>>;
    getCredentialTypes(resourceOptions?: HttpResourceOptions<Array<UsrCredentialType>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<UsrCredentialType> | undefined>;
    /** Returns credential types */
    getCredentialTypes(resourceOptions?: HttpResourceOptions<Array<UsrCredentialType>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<UsrCredentialType> | undefined> {
        return httpResource(() => {
            return {
                url: `${this.basePath}/api/credentials/types`,
                method: "GET",
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    createRandomSecret(length: Signal<number | undefined> | number | undefined, resourceOptions: HttpResourceOptions<CredentialSecretResponse, unknown> & { defaultValue: NoInfer<CredentialSecretResponse> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<CredentialSecretResponse>;
    createRandomSecret(length?: Signal<number | undefined> | number, resourceOptions?: HttpResourceOptions<CredentialSecretResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<CredentialSecretResponse | undefined>;
    /** Returns random secret (as string) */
    createRandomSecret(length?: Signal<number | undefined> | number, resourceOptions?: HttpResourceOptions<CredentialSecretResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<CredentialSecretResponse | undefined> {
        return httpResource(() => {
            let params = new HttpParams();
            const lengthValue = typeof length === 'function' ? length() : length;
            if (lengthValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, lengthValue, 'length');
            }
            return {
                url: `${this.basePath}/api/credentials/randomsecret`,
                method: "GET",
                params,
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    getPermissions(uri: Signal<string> | string, resourceOptions: HttpResourceOptions<PermissionResponse, unknown> & { defaultValue: NoInfer<PermissionResponse> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<PermissionResponse>;
    getPermissions(uri: Signal<string> | string, resourceOptions?: HttpResourceOptions<PermissionResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<PermissionResponse | undefined>;
    /** Returns permission set for collection */
    getPermissions(uri: Signal<string> | string, resourceOptions?: HttpResourceOptions<PermissionResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<PermissionResponse | undefined> {
        return httpResource(() => {
            let params = new HttpParams();
            const uriValue = typeof uri === 'function' ? uri() : uri;
            if (uriValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, uriValue, 'uri');
            }
            return {
                url: `${this.basePath}/api/permission`,
                method: "GET",
                params,
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    getPermissionsSelf(resourceOptions: HttpResourceOptions<PermissionResponse, unknown> & { defaultValue: NoInfer<PermissionResponse> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<PermissionResponse>;
    getPermissionsSelf(resourceOptions?: HttpResourceOptions<PermissionResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<PermissionResponse | undefined>;
    /** Returns permission set for current user */
    getPermissionsSelf(resourceOptions?: HttpResourceOptions<PermissionResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<PermissionResponse | undefined> {
        return httpResource(() => {
            return {
                url: `${this.basePath}/api/permission/self`,
                method: "GET",
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    getPrivilegesIncoming(grantee: Signal<string | undefined> | string | undefined, empty: Signal<boolean | undefined> | boolean | undefined, transitive: Signal<boolean | undefined> | boolean | undefined, resourceOptions: HttpResourceOptions<PrivilegeResponse, unknown> & { defaultValue: NoInfer<PrivilegeResponse> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<PrivilegeResponse>;
    getPrivilegesIncoming(grantee?: Signal<string | undefined> | string, empty?: Signal<boolean | undefined> | boolean, transitive?: Signal<boolean | undefined> | boolean, resourceOptions?: HttpResourceOptions<PrivilegeResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<PrivilegeResponse | undefined>;
    getPrivilegesIncoming(grantee?: Signal<string | undefined> | string, empty?: Signal<boolean | undefined> | boolean, transitive?: Signal<boolean | undefined> | boolean, resourceOptions?: HttpResourceOptions<PrivilegeResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<PrivilegeResponse | undefined> {
        return httpResource(() => {
            let params = new HttpParams();
            const granteeValue = typeof grantee === 'function' ? grantee() : grantee;
            if (granteeValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, granteeValue, 'grantee');
            }
            const emptyValue = typeof empty === 'function' ? empty() : empty;
            if (emptyValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, emptyValue, 'empty');
            }
            const transitiveValue = typeof transitive === 'function' ? transitive() : transitive;
            if (transitiveValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, transitiveValue, 'transitive');
            }
            return {
                url: `${this.basePath}/api/privilege`,
                method: "GET",
                params,
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    getPrivilegesOutgoing(grantor: Signal<string | undefined> | string | undefined, empty: Signal<boolean | undefined> | boolean | undefined, transitive: Signal<boolean | undefined> | boolean | undefined, resourceOptions: HttpResourceOptions<PrivilegeResponse, unknown> & { defaultValue: NoInfer<PrivilegeResponse> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<PrivilegeResponse>;
    getPrivilegesOutgoing(grantor?: Signal<string | undefined> | string, empty?: Signal<boolean | undefined> | boolean, transitive?: Signal<boolean | undefined> | boolean, resourceOptions?: HttpResourceOptions<PrivilegeResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<PrivilegeResponse | undefined>;
    getPrivilegesOutgoing(grantor?: Signal<string | undefined> | string, empty?: Signal<boolean | undefined> | boolean, transitive?: Signal<boolean | undefined> | boolean, resourceOptions?: HttpResourceOptions<PrivilegeResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<PrivilegeResponse | undefined> {
        return httpResource(() => {
            let params = new HttpParams();
            const grantorValue = typeof grantor === 'function' ? grantor() : grantor;
            if (grantorValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, grantorValue, 'grantor');
            }
            const emptyValue = typeof empty === 'function' ? empty() : empty;
            if (emptyValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, emptyValue, 'empty');
            }
            const transitiveValue = typeof transitive === 'function' ? transitive() : transitive;
            if (transitiveValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, transitiveValue, 'transitive');
            }
            return {
                url: `${this.basePath}/api/privilege/grants`,
                method: "GET",
                params,
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    getMemberships(principal: Signal<string | undefined> | string | undefined, direction: Signal<MembershipDirection | undefined> | MembershipDirection | undefined, resourceOptions: HttpResourceOptions<MembershipResponse, unknown> & { defaultValue: NoInfer<MembershipResponse> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<MembershipResponse>;
    getMemberships(principal?: Signal<string | undefined> | string, direction?: Signal<MembershipDirection | undefined> | MembershipDirection, resourceOptions?: HttpResourceOptions<MembershipResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<MembershipResponse | undefined>;
    getMemberships(principal?: Signal<string | undefined> | string, direction?: Signal<MembershipDirection | undefined> | MembershipDirection, resourceOptions?: HttpResourceOptions<MembershipResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<MembershipResponse | undefined> {
        return httpResource(() => {
            let params = new HttpParams();
            const principalValue = typeof principal === 'function' ? principal() : principal;
            if (principalValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, principalValue, 'principal');
            }
            const directionValue = typeof direction === 'function' ? direction() : direction;
            if (directionValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, directionValue, 'direction');
            }
            return {
                url: `${this.basePath}/api/membership`,
                method: "GET",
                params,
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    getGroupMembers(groupName: Signal<string> | string, principal: Signal<string | undefined> | string | undefined, resourceOptions: HttpResourceOptions<Array<GroupMemberRef>, unknown> & { defaultValue: NoInfer<Array<GroupMemberRef>> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<GroupMemberRef>>;
    getGroupMembers(groupName: Signal<string> | string, principal?: Signal<string | undefined> | string, resourceOptions?: HttpResourceOptions<Array<GroupMemberRef>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<GroupMemberRef> | undefined>;
    getGroupMembers(groupName: Signal<string> | string, principal?: Signal<string | undefined> | string, resourceOptions?: HttpResourceOptions<Array<GroupMemberRef>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<GroupMemberRef> | undefined> {
        return httpResource(() => {
            let params = new HttpParams();
            const principalValue = typeof principal === 'function' ? principal() : principal;
            if (principalValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, principalValue, 'principal');
            }
            return {
                url: `${this.basePath}/api/membership/group/${typeof groupName === 'function' ? groupName() : groupName}`,
                method: "GET",
                params,
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    getProxyMembers(relType: Signal<RelationshipTypes> | RelationshipTypes, principal: Signal<string | undefined> | string | undefined, resourceOptions: HttpResourceOptions<Array<GroupMemberRef>, unknown> & { defaultValue: NoInfer<Array<GroupMemberRef>> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<GroupMemberRef>>;
    getProxyMembers(relType: Signal<RelationshipTypes> | RelationshipTypes, principal?: Signal<string | undefined> | string, resourceOptions?: HttpResourceOptions<Array<GroupMemberRef>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<GroupMemberRef> | undefined>;
    /** By default the own proxy group members are returned, otherwise from the given principal */
    getProxyMembers(relType: Signal<RelationshipTypes> | RelationshipTypes, principal?: Signal<string | undefined> | string, resourceOptions?: HttpResourceOptions<Array<GroupMemberRef>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<GroupMemberRef> | undefined> {
        return httpResource(() => {
            let params = new HttpParams();
            const principalValue = typeof principal === 'function' ? principal() : principal;
            if (principalValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, principalValue, 'principal');
            }
            return {
                url: `${this.basePath}/api/membership/proxy/${typeof relType === 'function' ? relType() : relType}`,
                method: "GET",
                params,
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    getCollectionByOwner(username: Signal<string> | string, resourceOptions: HttpResourceOptions<Array<CollectionResponse>, unknown> & { defaultValue: NoInfer<Array<CollectionResponse>> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<CollectionResponse>>;
    getCollectionByOwner(username: Signal<string> | string, resourceOptions?: HttpResourceOptions<Array<CollectionResponse>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<CollectionResponse> | undefined>;
    /** Returns principal user collections. */
    getCollectionByOwner(username: Signal<string> | string, resourceOptions?: HttpResourceOptions<Array<CollectionResponse>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<CollectionResponse> | undefined> {
        return httpResource(() => {
            return {
                url: `${this.basePath}/api/collection/${typeof username === 'function' ? username() : username}`,
                method: "GET",
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    getCollectionByUri(uri: Signal<string> | string, resourceOptions: HttpResourceOptions<CollectionResponse, unknown> & { defaultValue: NoInfer<CollectionResponse> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<CollectionResponse>;
    getCollectionByUri(uri: Signal<string> | string, resourceOptions?: HttpResourceOptions<CollectionResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<CollectionResponse | undefined>;
    /** Returns collection. */
    getCollectionByUri(uri: Signal<string> | string, resourceOptions?: HttpResourceOptions<CollectionResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<CollectionResponse | undefined> {
        return httpResource(() => {
            let params = new HttpParams();
            const uriValue = typeof uri === 'function' ? uri() : uri;
            if (uriValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, uriValue, 'uri');
            }
            return {
                url: `${this.basePath}/api/collection`,
                method: "GET",
                params,
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    getObjectById(id: Signal<number> | number, resourceOptions: HttpResourceOptions<CalendarScheduleItem, unknown> & { defaultValue: NoInfer<CalendarScheduleItem> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<CalendarScheduleItem>;
    getObjectById(id: Signal<number> | number, resourceOptions?: HttpResourceOptions<CalendarScheduleItem, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<CalendarScheduleItem | undefined>;
    /** Returns object or not found. */
    getObjectById(id: Signal<number> | number, resourceOptions?: HttpResourceOptions<CalendarScheduleItem, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<CalendarScheduleItem | undefined> {
        return httpResource(() => {
            return {
                url: `${this.basePath}/api/object/id/calendar/${typeof id === 'function' ? id() : id}`,
                method: "GET",
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    getObjectsByUid(uid: Signal<string> | string, resourceOptions: HttpResourceOptions<Array<CalendarScheduleItem>, unknown> & { defaultValue: NoInfer<Array<CalendarScheduleItem>> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<CalendarScheduleItem>>;
    getObjectsByUid(uid: Signal<string> | string, resourceOptions?: HttpResourceOptions<Array<CalendarScheduleItem>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<CalendarScheduleItem> | undefined>;
    /** Returns objects. */
    getObjectsByUid(uid: Signal<string> | string, resourceOptions?: HttpResourceOptions<Array<CalendarScheduleItem>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<CalendarScheduleItem> | undefined> {
        return httpResource(() => {
            return {
                url: `${this.basePath}/api/object/uid/calendar/${typeof uid === 'function' ? uid() : uid}`,
                method: "GET",
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    getCalendarByUid(uid: Signal<string> | string, resourceOptions: HttpResourceOptions<Array<CalendarScheduleItem>, unknown> & { defaultValue: NoInfer<Array<CalendarScheduleItem>> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<CalendarScheduleItem>>;
    getCalendarByUid(uid: Signal<string> | string, resourceOptions?: HttpResourceOptions<Array<CalendarScheduleItem>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<CalendarScheduleItem> | undefined>;
    /** Returns calendar entries */
    getCalendarByUid(uid: Signal<string> | string, resourceOptions?: HttpResourceOptions<Array<CalendarScheduleItem>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<CalendarScheduleItem> | undefined> {
        return httpResource(() => {
            return {
                url: `${this.basePath}/api/calendar/uid/${typeof uid === 'function' ? uid() : uid}`,
                method: "GET",
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    getCalendar(path: Signal<string | undefined> | string | undefined, resourceOptions: HttpResourceOptions<Array<CalendarScheduleItem>, unknown> & { defaultValue: NoInfer<Array<CalendarScheduleItem>> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<CalendarScheduleItem>>;
    getCalendar(path?: Signal<string | undefined> | string, resourceOptions?: HttpResourceOptions<Array<CalendarScheduleItem>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<CalendarScheduleItem> | undefined>;
    /** Returns calendar entries */
    getCalendar(path?: Signal<string | undefined> | string, resourceOptions?: HttpResourceOptions<Array<CalendarScheduleItem>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<CalendarScheduleItem> | undefined> {
        return httpResource(() => {
            let params = new HttpParams();
            const pathValue = typeof path === 'function' ? path() : path;
            if (pathValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, pathValue, 'path');
            }
            return {
                url: `${this.basePath}/api/calendar/uri`,
                method: "GET",
                params,
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    getAddressbook(collection: Signal<string | undefined> | string | undefined, resourceOptions: HttpResourceOptions<Array<AddressbookItem>, unknown> & { defaultValue: NoInfer<Array<AddressbookItem>> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<AddressbookItem>>;
    getAddressbook(collection?: Signal<string | undefined> | string, resourceOptions?: HttpResourceOptions<Array<AddressbookItem>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<AddressbookItem> | undefined>;
    /** Returns addressbook entries */
    getAddressbook(collection?: Signal<string | undefined> | string, resourceOptions?: HttpResourceOptions<Array<AddressbookItem>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<AddressbookItem> | undefined> {
        return httpResource(() => {
            let params = new HttpParams();
            const collectionValue = typeof collection === 'function' ? collection() : collection;
            if (collectionValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, collectionValue, 'collection');
            }
            return {
                url: `${this.basePath}/api/addressbook/uri`,
                method: "GET",
                params,
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    getMailboxByUid(uid: Signal<string> | string, resourceOptions: HttpResourceOptions<Array<MailboxItem>, unknown> & { defaultValue: NoInfer<Array<MailboxItem>> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<MailboxItem>>;
    getMailboxByUid(uid: Signal<string> | string, resourceOptions?: HttpResourceOptions<Array<MailboxItem>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<MailboxItem> | undefined>;
    /** Returns mailbox items. */
    getMailboxByUid(uid: Signal<string> | string, resourceOptions?: HttpResourceOptions<Array<MailboxItem>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<MailboxItem> | undefined> {
        return httpResource(() => {
            return {
                url: `${this.basePath}/api/mailbox/uid/${typeof uid === 'function' ? uid() : uid}`,
                method: "GET",
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }

    getMailboxBySender(sender: Signal<string> | string, resourceOptions: HttpResourceOptions<Array<MailboxItem>, unknown> & { defaultValue: NoInfer<Array<MailboxItem>> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<MailboxItem>>;
    getMailboxBySender(sender: Signal<string> | string, resourceOptions?: HttpResourceOptions<Array<MailboxItem>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<MailboxItem> | undefined>;
    /** Returns mailbox items. */
    getMailboxBySender(sender: Signal<string> | string, resourceOptions?: HttpResourceOptions<Array<MailboxItem>, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<Array<MailboxItem> | undefined> {
        return httpResource(() => {
            let params = new HttpParams();
            const senderValue = typeof sender === 'function' ? sender() : sender;
            if (senderValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, senderValue, 'sender');
            }
            return {
                url: `${this.basePath}/api/mailbox`,
                method: "GET",
                params,
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }
}
