/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated service exports
* Do not edit this file manually
*/
export { CalendareResource } from "./calendare.resource";
export { TestingResource } from "./testing.resource";
