/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* `httpResource` is still an experimental feature - NOT PRODUCTION READY
* Generated Angular service for TestingResource
* Do not edit this file manually
*/
import { HttpContext, HttpContextToken, HttpHeaders, HttpParams, httpResource, HttpResourceOptions, HttpResourceRef, HttpResourceRequest } from "@angular/common/http";
import { inject, Injectable, Signal } from "@angular/core";
import { BASE_PATH_CALENDAREAPI, CLIENT_CONTEXT_TOKEN_CALENDAREAPI } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { SyncTokenResponse } from "../models";

@Injectable({ providedIn: "root" })
export class TestingResource {
    private readonly basePath: string = inject(BASE_PATH_CALENDAREAPI);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_CALENDAREAPI;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'CalendareApi');
    }

    getLatestSyncToken(collection: Signal<string> | string, resourceOptions: HttpResourceOptions<SyncTokenResponse, unknown> & { defaultValue: NoInfer<SyncTokenResponse> }, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<SyncTokenResponse>;
    getLatestSyncToken(collection: Signal<string> | string, resourceOptions?: HttpResourceOptions<SyncTokenResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<SyncTokenResponse | undefined>;
    /** Gets the latest sync token for a collection, only for test automation */
    getLatestSyncToken(collection: Signal<string> | string, resourceOptions?: HttpResourceOptions<SyncTokenResponse, unknown>, requestOptions?: Omit<HttpResourceRequest, "method" | "url" | "params">): HttpResourceRef<SyncTokenResponse | undefined> {
        return httpResource(() => {
            let params = new HttpParams();
            const collectionValue = typeof collection === 'function' ? collection() : collection;
            if (collectionValue != null) {
                params = HttpParamsBuilder.addToHttpParams(params, collectionValue, 'collection');
            }
            return {
                url: `${this.basePath}/api/sync`,
                method: "GET",
                params,
                context: this.createContextWithClientId(requestOptions?.context),
                ...requestOptions
            }
        }, resourceOptions);
    }
}
