// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Calendare controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_CALENDAREAPI, CLIENT_CONTEXT_TOKEN_CALENDAREAPI } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, FeatureResponse, PrincipalResponse, UserRegisterRequest, UserAmendRequest, UserConfirmEmailRequest, CredentialResponse, UserCredentialCreateRequest, CredentialCreateResponse, UsrCredentialType, CredentialSecretResponse, UserCredentialResetRequest, UserCredentialLoginRequest, PermissionResponse, PermissionRequest, PrivilegeResponse, PrivilegeRequest, MembershipDirection, MembershipResponse, MembershipRequest, GroupMemberRef, RelationshipTypes, CollectionResponse, CollectionCreateRequest, CollectionAmendRequest, CalendarScheduleItem, AddressbookItem, MailboxItem } from "../models";

@Injectable({ providedIn: "root" })
export class CalendareService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_CALENDAREAPI);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_CALENDAREAPI;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'CalendareApi');
    }

    getVersion(observe?: 'body', options?: RequestOptions<'json'>): Observable<FeatureResponse>;
    getVersion(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FeatureResponse>>;
    getVersion(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FeatureResponse>>;
    /** Get version and features by calender client information */
    getVersion(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/version`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    ping(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    ping(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    ping(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    ping(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/site/ping`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getUserList(types: Array<string>, search?: string, unrestricted?: boolean, technical?: boolean, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<PrincipalResponse>>;
    getUserList(types: Array<string>, search?: string, unrestricted?: boolean, technical?: boolean, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<PrincipalResponse>>>;
    getUserList(types: Array<string>, search?: string, unrestricted?: boolean, technical?: boolean, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<PrincipalResponse>>>;
    /** Returns visible principals */
    getUserList(types: Array<string>, search?: string, unrestricted?: boolean, technical?: boolean, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/user`;

        let params = new HttpParams();
        if (search != null) {
            params = HttpParamsBuilder.addToHttpParams(params, search, 'search');
        }
        if (types != null) {
            params = HttpParamsBuilder.addToHttpParams(params, types, 'types');
        }
        if (unrestricted != null) {
            params = HttpParamsBuilder.addToHttpParams(params, unrestricted, 'unrestricted');
        }
        if (technical != null) {
            params = HttpParamsBuilder.addToHttpParams(params, technical, 'technical');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    createUser(userRegisterRequest: UserRegisterRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    createUser(userRegisterRequest: UserRegisterRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    createUser(userRegisterRequest: UserRegisterRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    createUser(userRegisterRequest: UserRegisterRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/user`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: userRegisterRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getUser(username: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<PrincipalResponse>;
    getUser(username: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PrincipalResponse>>;
    getUser(username: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PrincipalResponse>>;
    /** Returns principal */
    getUser(username: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/user/${username}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    updateUser(username: string, userAmendRequest: UserAmendRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<PrincipalResponse>;
    updateUser(username: string, userAmendRequest: UserAmendRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PrincipalResponse>>;
    updateUser(username: string, userAmendRequest: UserAmendRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PrincipalResponse>>;
    /** Returns user registration data */
    updateUser(username: string, userAmendRequest: UserAmendRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/user/${username}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: userAmendRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deleteUser(username: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    deleteUser(username: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    deleteUser(username: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Deletes a user with all related data (calendars, addressbooks, ...) */
    deleteUser(username: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/user/${username}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    confirmUserEmail(username: string, userConfirmEmailRequest: UserConfirmEmailRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<PrincipalResponse>;
    confirmUserEmail(username: string, userConfirmEmailRequest: UserConfirmEmailRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PrincipalResponse>>;
    confirmUserEmail(username: string, userConfirmEmailRequest: UserConfirmEmailRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PrincipalResponse>>;
    /** Returns user registration data */
    confirmUserEmail(username: string, userConfirmEmailRequest: UserConfirmEmailRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/user/${username}/email/confirm`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('patch', url, {
            body: userConfirmEmailRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    sendEmailConfirmationCode(username: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<PrincipalResponse>;
    sendEmailConfirmationCode(username: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PrincipalResponse>>;
    sendEmailConfirmationCode(username: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PrincipalResponse>>;
    /** Returns user registration data */
    sendEmailConfirmationCode(username: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/user/${username}/email/generate`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('patch', url, {
            body: null,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getPrincipalOfMyself(observe?: 'body', options?: RequestOptions<'json'>): Observable<PrincipalResponse>;
    getPrincipalOfMyself(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PrincipalResponse>>;
    getPrincipalOfMyself(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PrincipalResponse>>;
    /** Returns current user's basic infos */
    getPrincipalOfMyself(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/credentials`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getCredentialsOfUser(username: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<CredentialResponse>>;
    getCredentialsOfUser(username: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<CredentialResponse>>>;
    getCredentialsOfUser(username: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<CredentialResponse>>>;
    /** Returns credential entries */
    getCredentialsOfUser(username: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/credentials/user/${username}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    createCredential(username: string, userCredentialCreateRequest: UserCredentialCreateRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<CredentialCreateResponse>;
    createCredential(username: string, userCredentialCreateRequest: UserCredentialCreateRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CredentialCreateResponse>>;
    createCredential(username: string, userCredentialCreateRequest: UserCredentialCreateRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CredentialCreateResponse>>;
    createCredential(username: string, userCredentialCreateRequest: UserCredentialCreateRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/credentials/user/${username}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: userCredentialCreateRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getCredentialOfUser(username: string, credentialSubject: string, credentialType?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<CredentialResponse>;
    getCredentialOfUser(username: string, credentialSubject: string, credentialType?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CredentialResponse>>;
    getCredentialOfUser(username: string, credentialSubject: string, credentialType?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CredentialResponse>>;
    /** Returns credential */
    getCredentialOfUser(username: string, credentialSubject: string, credentialType?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/credentials/user/${username}/${credentialSubject}`;

        let params = new HttpParams();
        if (credentialType != null) {
            params = HttpParamsBuilder.addToHttpParams(params, credentialType, 'credentialType');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deleteCredential(username: string, credentialSubject: string, credentialType?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    deleteCredential(username: string, credentialSubject: string, credentialType?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    deleteCredential(username: string, credentialSubject: string, credentialType?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    deleteCredential(username: string, credentialSubject: string, credentialType?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/credentials/user/${username}/${credentialSubject}`;

        let params = new HttpParams();
        if (credentialType != null) {
            params = HttpParamsBuilder.addToHttpParams(params, credentialType, 'credentialType');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getCredentialTypes(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<UsrCredentialType>>;
    getCredentialTypes(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<UsrCredentialType>>>;
    getCredentialTypes(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<UsrCredentialType>>>;
    /** Returns credential types */
    getCredentialTypes(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/credentials/types`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    createRandomSecret(length?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<CredentialSecretResponse>;
    createRandomSecret(length?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CredentialSecretResponse>>;
    createRandomSecret(length?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CredentialSecretResponse>>;
    /** Returns random secret (as string) */
    createRandomSecret(length?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/credentials/randomsecret`;

        let params = new HttpParams();
        if (length != null) {
            params = HttpParamsBuilder.addToHttpParams(params, length, 'length');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    lockCredential(username: string, credentialSubject: string, credentialType?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<CredentialResponse>;
    lockCredential(username: string, credentialSubject: string, credentialType?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CredentialResponse>>;
    lockCredential(username: string, credentialSubject: string, credentialType?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CredentialResponse>>;
    /** Returns credential entry */
    lockCredential(username: string, credentialSubject: string, credentialType?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/credentials/user/${username}/${credentialSubject}/lock`;

        let params = new HttpParams();
        if (credentialType != null) {
            params = HttpParamsBuilder.addToHttpParams(params, credentialType, 'credentialType');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('patch', url, {
            body: null,
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    unlockCredential(username: string, credentialSubject: string, credentialType?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<CredentialResponse>;
    unlockCredential(username: string, credentialSubject: string, credentialType?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CredentialResponse>>;
    unlockCredential(username: string, credentialSubject: string, credentialType?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CredentialResponse>>;
    /** Returns credential entry */
    unlockCredential(username: string, credentialSubject: string, credentialType?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/credentials/user/${username}/${credentialSubject}/lock`;

        let params = new HttpParams();
        if (credentialType != null) {
            params = HttpParamsBuilder.addToHttpParams(params, credentialType, 'credentialType');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    setCredentialPassword(username: string, credentialSubject: string, userCredentialResetRequest?: UserCredentialResetRequest, credentialType?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<CredentialCreateResponse>;
    setCredentialPassword(username: string, credentialSubject: string, userCredentialResetRequest?: UserCredentialResetRequest, credentialType?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CredentialCreateResponse>>;
    setCredentialPassword(username: string, credentialSubject: string, userCredentialResetRequest?: UserCredentialResetRequest, credentialType?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CredentialCreateResponse>>;
    /** Returns credential entry with secret */
    setCredentialPassword(username: string, credentialSubject: string, userCredentialResetRequest?: UserCredentialResetRequest, credentialType?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/credentials/user/${username}/${credentialSubject}/reset`;

        let params = new HttpParams();
        if (credentialType != null) {
            params = HttpParamsBuilder.addToHttpParams(params, credentialType, 'credentialType');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('patch', url, {
            body: userCredentialResetRequest,
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    autoLinkCurrentUser(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    autoLinkCurrentUser(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    autoLinkCurrentUser(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    autoLinkCurrentUser(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/credentials/autolink`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('patch', url, {
            body: null,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    linkCurrentUser(sub: string, userCredentialLoginRequest: UserCredentialLoginRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    linkCurrentUser(sub: string, userCredentialLoginRequest: UserCredentialLoginRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    linkCurrentUser(sub: string, userCredentialLoginRequest: UserCredentialLoginRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Link user identified by a JWT bearer token to an existing principal, defined by username/password or accesskey/secret pair */
    linkCurrentUser(sub: string, userCredentialLoginRequest: UserCredentialLoginRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/credentials/link/${sub}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('patch', url, {
            body: userCredentialLoginRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    autoProvisionCurrentUser(userRegisterRequest: UserRegisterRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    autoProvisionCurrentUser(userRegisterRequest: UserRegisterRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    autoProvisionCurrentUser(userRegisterRequest: UserRegisterRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    autoProvisionCurrentUser(userRegisterRequest: UserRegisterRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/credentials/autoprovision`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: userRegisterRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getPermissions(uri: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<PermissionResponse>;
    getPermissions(uri: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PermissionResponse>>;
    getPermissions(uri: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PermissionResponse>>;
    /** Returns permission set for collection */
    getPermissions(uri: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/permission`;

        let params = new HttpParams();
        if (uri != null) {
            params = HttpParamsBuilder.addToHttpParams(params, uri, 'uri');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    setPermissions(permissionRequest: PermissionRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    setPermissions(permissionRequest: PermissionRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    setPermissions(permissionRequest: PermissionRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Returns permission set for collection */
    setPermissions(permissionRequest: PermissionRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/permission`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('patch', url, {
            body: permissionRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getPermissionsSelf(observe?: 'body', options?: RequestOptions<'json'>): Observable<PermissionResponse>;
    getPermissionsSelf(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PermissionResponse>>;
    getPermissionsSelf(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PermissionResponse>>;
    /** Returns permission set for current user */
    getPermissionsSelf(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/permission/self`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getPrivilegesIncoming(grantee?: string, empty?: boolean, transitive?: boolean, observe?: 'body', options?: RequestOptions<'json'>): Observable<PrivilegeResponse>;
    getPrivilegesIncoming(grantee?: string, empty?: boolean, transitive?: boolean, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PrivilegeResponse>>;
    getPrivilegesIncoming(grantee?: string, empty?: boolean, transitive?: boolean, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PrivilegeResponse>>;
    getPrivilegesIncoming(grantee?: string, empty?: boolean, transitive?: boolean, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/privilege`;

        let params = new HttpParams();
        if (grantee != null) {
            params = HttpParamsBuilder.addToHttpParams(params, grantee, 'grantee');
        }
        if (empty != null) {
            params = HttpParamsBuilder.addToHttpParams(params, empty, 'empty');
        }
        if (transitive != null) {
            params = HttpParamsBuilder.addToHttpParams(params, transitive, 'transitive');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    createPrivileges(privilegeRequest: PrivilegeRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    createPrivileges(privilegeRequest: PrivilegeRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    createPrivileges(privilegeRequest: PrivilegeRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Does not support custom privileges */
    createPrivileges(privilegeRequest: PrivilegeRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/privilege`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: privilegeRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getPrivilegesOutgoing(grantor?: string, empty?: boolean, transitive?: boolean, observe?: 'body', options?: RequestOptions<'json'>): Observable<PrivilegeResponse>;
    getPrivilegesOutgoing(grantor?: string, empty?: boolean, transitive?: boolean, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PrivilegeResponse>>;
    getPrivilegesOutgoing(grantor?: string, empty?: boolean, transitive?: boolean, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PrivilegeResponse>>;
    getPrivilegesOutgoing(grantor?: string, empty?: boolean, transitive?: boolean, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/privilege/grants`;

        let params = new HttpParams();
        if (grantor != null) {
            params = HttpParamsBuilder.addToHttpParams(params, grantor, 'grantor');
        }
        if (empty != null) {
            params = HttpParamsBuilder.addToHttpParams(params, empty, 'empty');
        }
        if (transitive != null) {
            params = HttpParamsBuilder.addToHttpParams(params, transitive, 'transitive');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    addPrivilege(grantee: string, grantor?: string, reltype?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    addPrivilege(grantee: string, grantor?: string, reltype?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    addPrivilege(grantee: string, grantor?: string, reltype?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    addPrivilege(grantee: string, grantor?: string, reltype?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/privilege/grants`;

        let params = new HttpParams();
        if (grantee != null) {
            params = HttpParamsBuilder.addToHttpParams(params, grantee, 'grantee');
        }
        if (grantor != null) {
            params = HttpParamsBuilder.addToHttpParams(params, grantor, 'grantor');
        }
        if (reltype != null) {
            params = HttpParamsBuilder.addToHttpParams(params, reltype, 'reltype');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('put', url, {
            body: null,
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deletePrivileges(grantee: string, grantor?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    deletePrivileges(grantee: string, grantor?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    deletePrivileges(grantee: string, grantor?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    deletePrivileges(grantee: string, grantor?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/privilege/grants`;

        let params = new HttpParams();
        if (grantee != null) {
            params = HttpParamsBuilder.addToHttpParams(params, grantee, 'grantee');
        }
        if (grantor != null) {
            params = HttpParamsBuilder.addToHttpParams(params, grantor, 'grantor');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getMemberships(principal?: string, direction?: MembershipDirection, observe?: 'body', options?: RequestOptions<'json'>): Observable<MembershipResponse>;
    getMemberships(principal?: string, direction?: MembershipDirection, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<MembershipResponse>>;
    getMemberships(principal?: string, direction?: MembershipDirection, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<MembershipResponse>>;
    getMemberships(principal?: string, direction?: MembershipDirection, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/membership`;

        let params = new HttpParams();
        if (principal != null) {
            params = HttpParamsBuilder.addToHttpParams(params, principal, 'principal');
        }
        if (direction != null) {
            params = HttpParamsBuilder.addToHttpParams(params, direction, 'direction');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    createMemberships(membershipRequest: MembershipRequest, principal?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    createMemberships(membershipRequest: MembershipRequest, principal?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    createMemberships(membershipRequest: MembershipRequest, principal?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    createMemberships(membershipRequest: MembershipRequest, principal?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/membership`;

        let params = new HttpParams();
        if (principal != null) {
            params = HttpParamsBuilder.addToHttpParams(params, principal, 'principal');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: membershipRequest,
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getGroupMembers(groupName: string, principal?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<GroupMemberRef>>;
    getGroupMembers(groupName: string, principal?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<GroupMemberRef>>>;
    getGroupMembers(groupName: string, principal?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<GroupMemberRef>>>;
    getGroupMembers(groupName: string, principal?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/membership/group/${groupName}`;

        let params = new HttpParams();
        if (principal != null) {
            params = HttpParamsBuilder.addToHttpParams(params, principal, 'principal');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    addGroupmembership(groupName: string, memberName: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    addGroupmembership(groupName: string, memberName: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    addGroupmembership(groupName: string, memberName: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    addGroupmembership(groupName: string, memberName: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/membership/group/${groupName}/${memberName}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('put', url, {
            body: null,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deleteGroupmembership(groupName: string, memberName: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    deleteGroupmembership(groupName: string, memberName: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    deleteGroupmembership(groupName: string, memberName: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    deleteGroupmembership(groupName: string, memberName: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/membership/group/${groupName}/${memberName}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    recalcGroupmembership(principal?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    recalcGroupmembership(principal?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    recalcGroupmembership(principal?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Maintenance function, adding or removing members triggers this automatically */
    recalcGroupmembership(principal?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/membership/group`;

        let params = new HttpParams();
        if (principal != null) {
            params = HttpParamsBuilder.addToHttpParams(params, principal, 'principal');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('patch', url, {
            body: null,
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getProxyMembers(relType: RelationshipTypes, principal?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<GroupMemberRef>>;
    getProxyMembers(relType: RelationshipTypes, principal?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<GroupMemberRef>>>;
    getProxyMembers(relType: RelationshipTypes, principal?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<GroupMemberRef>>>;
    /** By default the own proxy group members are returned, otherwise from the given principal */
    getProxyMembers(relType: RelationshipTypes, principal?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/membership/proxy/${relType}`;

        let params = new HttpParams();
        if (principal != null) {
            params = HttpParamsBuilder.addToHttpParams(params, principal, 'principal');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    addProxyMembership(relType: RelationshipTypes, memberName: string, principal?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    addProxyMembership(relType: RelationshipTypes, memberName: string, principal?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    addProxyMembership(relType: RelationshipTypes, memberName: string, principal?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    addProxyMembership(relType: RelationshipTypes, memberName: string, principal?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/membership/proxy/${relType}/${memberName}`;

        let params = new HttpParams();
        if (principal != null) {
            params = HttpParamsBuilder.addToHttpParams(params, principal, 'principal');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('put', url, {
            body: null,
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deleteProxyMembership(relType: RelationshipTypes, memberName: string, principal?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    deleteProxyMembership(relType: RelationshipTypes, memberName: string, principal?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    deleteProxyMembership(relType: RelationshipTypes, memberName: string, principal?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    deleteProxyMembership(relType: RelationshipTypes, memberName: string, principal?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/membership/proxy/${relType}/${memberName}`;

        let params = new HttpParams();
        if (principal != null) {
            params = HttpParamsBuilder.addToHttpParams(params, principal, 'principal');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getCollectionByOwner(username: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<CollectionResponse>>;
    getCollectionByOwner(username: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<CollectionResponse>>>;
    getCollectionByOwner(username: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<CollectionResponse>>>;
    /** Returns principal user collections. */
    getCollectionByOwner(username: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/collection/${username}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getCollectionByUri(uri: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<CollectionResponse>;
    getCollectionByUri(uri: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CollectionResponse>>;
    getCollectionByUri(uri: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CollectionResponse>>;
    /** Returns collection. */
    getCollectionByUri(uri: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/collection`;

        let params = new HttpParams();
        if (uri != null) {
            params = HttpParamsBuilder.addToHttpParams(params, uri, 'uri');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    createCollection(collectionCreateRequest: CollectionCreateRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    createCollection(collectionCreateRequest: CollectionCreateRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    createCollection(collectionCreateRequest: CollectionCreateRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Creates a collection. */
    createCollection(collectionCreateRequest: CollectionCreateRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/collection`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: collectionCreateRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    amendCollectionByUri(collectionAmendRequest: CollectionAmendRequest, uri: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    amendCollectionByUri(collectionAmendRequest: CollectionAmendRequest, uri: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    amendCollectionByUri(collectionAmendRequest: CollectionAmendRequest, uri: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Returns collection. */
    amendCollectionByUri(collectionAmendRequest: CollectionAmendRequest, uri: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/collection`;

        let params = new HttpParams();
        if (uri != null) {
            params = HttpParamsBuilder.addToHttpParams(params, uri, 'uri');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: collectionAmendRequest,
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deleteCollectionByUri(uri: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    deleteCollectionByUri(uri: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    deleteCollectionByUri(uri: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Delete collection including all contained collections and items */
    deleteCollectionByUri(uri: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/collection`;

        let params = new HttpParams();
        if (uri != null) {
            params = HttpParamsBuilder.addToHttpParams(params, uri, 'uri');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getObjectById(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<CalendarScheduleItem>;
    getObjectById(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CalendarScheduleItem>>;
    getObjectById(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CalendarScheduleItem>>;
    /** Returns object or not found. */
    getObjectById(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/object/id/calendar/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getObjectsByUid(uid: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<CalendarScheduleItem>>;
    getObjectsByUid(uid: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<CalendarScheduleItem>>>;
    getObjectsByUid(uid: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<CalendarScheduleItem>>>;
    /** Returns objects. */
    getObjectsByUid(uid: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/object/uid/calendar/${uid}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getCalendarByUid(uid: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<CalendarScheduleItem>>;
    getCalendarByUid(uid: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<CalendarScheduleItem>>>;
    getCalendarByUid(uid: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<CalendarScheduleItem>>>;
    /** Returns calendar entries */
    getCalendarByUid(uid: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/calendar/uid/${uid}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getCalendar(path?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<CalendarScheduleItem>>;
    getCalendar(path?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<CalendarScheduleItem>>>;
    getCalendar(path?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<CalendarScheduleItem>>>;
    /** Returns calendar entries */
    getCalendar(path?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/calendar/uri`;

        let params = new HttpParams();
        if (path != null) {
            params = HttpParamsBuilder.addToHttpParams(params, path, 'path');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getAddressbook(collection?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<AddressbookItem>>;
    getAddressbook(collection?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<AddressbookItem>>>;
    getAddressbook(collection?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<AddressbookItem>>>;
    /** Returns addressbook entries */
    getAddressbook(collection?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/addressbook/uri`;

        let params = new HttpParams();
        if (collection != null) {
            params = HttpParamsBuilder.addToHttpParams(params, collection, 'collection');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getMailboxByUid(uid: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<MailboxItem>>;
    getMailboxByUid(uid: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<MailboxItem>>>;
    getMailboxByUid(uid: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<MailboxItem>>>;
    /** Returns mailbox items. */
    getMailboxByUid(uid: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/mailbox/uid/${uid}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getMailboxBySender(sender: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<MailboxItem>>;
    getMailboxBySender(sender: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<MailboxItem>>>;
    getMailboxBySender(sender: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<MailboxItem>>>;
    /** Returns mailbox items. */
    getMailboxBySender(sender: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/mailbox`;

        let params = new HttpParams();
        if (sender != null) {
            params = HttpParamsBuilder.addToHttpParams(params, sender, 'sender');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
