/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Testing controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_CALENDAREAPI, CLIENT_CONTEXT_TOKEN_CALENDAREAPI } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, SyncTokenResponse } from "../models";

@Injectable({ providedIn: "root" })
export class TestingService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_CALENDAREAPI);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_CALENDAREAPI;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'CalendareApi');
    }

    getLatestSyncToken(collection: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<SyncTokenResponse>;
    getLatestSyncToken(collection: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SyncTokenResponse>>;
    getLatestSyncToken(collection: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SyncTokenResponse>>;
    /** Gets the latest sync token for a collection, only for test automation */
    getLatestSyncToken(collection: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/sync`;

        let params = new HttpParams();
        if (collection != null) {
            params = HttpParamsBuilder.addToHttpParams(params, collection, 'collection');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
