/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface AddressbookItem {
    uri?: string | null;
    uid?: string | null;
    etag?: string | null;
    rawData?: string | null;
    vObjectType?: string | null;
    created?: Date;
    modified?: Date;
    formattedName?: string | null;
    name?: string | null;
    nickName?: string | null;
}

export enum CalendarClientType {
    NotDetected = "NotDetected",
    Thunderbird = "Thunderbird",
    MacOSCalendar = "MacOSCalendar",
    EMClient = "EMClient",
    DAVx5 = "DAVx5",
    Default = "Default"
}

export interface CalendarScheduleItem {
    uri?: string | null;
    uid?: string | null;
    etag?: string | null;
    scheduleTag?: string | null;
    rawData?: string | null;
    vObjectType?: string | null;
    created?: Date;
    modified?: Date;
    lastModified?: Date | null;
    dtstamp?: Date | null;
    dtstart?: Date | null;
    dtend?: Date | null;
    due?: Date | null;
    summary?: string | null;
    location?: string | null;
    description?: string | null;
    priority?: number | null;
    class?: string | null;
    transp?: string | null;
    rrule?: string | null;
    url?: string | null;
    percentComplete?: number;
    timezone?: string | null;
    status?: string | null;
    completed?: Date | null;
    firstInstanceStart?: Date | null;
    lastInstanceEnd?: Date | null;
    dtstartOrig?: Date | null;
    dtendOrig?: Date | null;
}

export enum CalendareFeatures {
    CalendarProxy = "CalendarProxy",
    VirtualProxyMembers = "VirtualProxyMembers",
    ResourceSharing = "ResourceSharing",
    AutoScheduling = "AutoScheduling",
    WebdavPush = "WebdavPush",
    VCard4 = "VCard4",
    SyncCollectionSuppressTokenGone = "SyncCollectionSuppressTokenGone"
}

export interface CollectionAmendRequest {
    uri?: string | null;
    displayName?: string | null;
    description?: string | null;
    color?: string | null;
    excludeFreeBusy?: boolean | null;
    timezone?: string | null;
}

export interface CollectionCreateRequest {
    uri: string | null;
    displayName?: string | null;
    collectionType?: CollectionType;
    description?: string | null;
    color?: string | null;
    scheduleTransparency?: string | null;
    timezone?: string | null;
    publicEventsOnly?: boolean;
    publiclyReadable?: boolean;
}

export interface CollectionResponse {
    id: number;
    uri: string | null;
    ownerUsername?: string | null;
    displayName?: string | null;
    collectionType?: CollectionType;
    collectionSubType?: CollectionSubType;
    description?: string | null;
    color?: string | null;
    scheduleTransparency?: string | null;
    excludeFreeBusy?: boolean;
    timezone?: string | null;
    parentContainerUri?: string | null;
    publicEventsOnly?: boolean;
    publiclyReadable?: boolean;
    isDefault?: boolean;
    isTechnical?: boolean;
    permissions?: PrivilegeMask;
    ownerProhibit?: PrivilegeMask;
    authorizedProhibit?: PrivilegeMask;
    globalPermitSelf?: PrivilegeMask;
    created?: Date;
    modified?: Date;
}

export enum CollectionSubType {
    Default = "Default",
    SchedulingOutbox = "SchedulingOutbox",
    SchedulingInbox = "SchedulingInbox",
    CalendarProxyRead = "CalendarProxyRead",
    CalendarProxyWrite = "CalendarProxyWrite",
    WebPushSubscription = "WebPushSubscription"
}

export enum CollectionType {
    Collection = "Collection",
    Principal = "Principal",
    Calendar = "Calendar",
    Addressbook = "Addressbook"
}

export interface CredentialResponse {
    id?: number;
    subject?: string | null;
    usrId?: number;
    username?: string | null;
    email?: string | null;
    emailOk?: Date | null;
    credentialType?: UsrCredentialType;
    credentialTypeId?: number;
    lastUsed?: Date | null;
    locked?: Date | null;
    created?: Date;
    modified?: Date;
}

export interface CredentialSecretResponse {
    secret?: string | null;
}

export interface FeatureByClient {
    clientType: CalendarClientType;
    enabled?: Array<CalendareFeatures>;
}

export interface FeatureResponse {
    version: string | null;
    pathBase: string | null;
    dbmsSchema?: Array<string>;
    dbmsDataMigrations?: Array<string>;
    features?: Array<CalendareFeatures>;
    featuresEnabled?: Array<FeatureByClient>;
}

export interface GroupMemberRef {
    uri: string | null;
    username?: string | null;
    displayname?: string | null;
    ownerDisplayname?: string | null;
    principalType?: string | null;
    membershipType?: MembershipPrivilegeType;
    isVirtual?: boolean | null;
}

export interface GroupRef {
    group: GroupMemberRef;
    members?: Array<GroupMemberRef>;
}

export interface MailboxItem {
    uid?: string | null;
    sequence?: number;
    senderEmail?: string | null;
    receiverEmail?: string | null;
    body?: string | null;
    created?: Date;
    processed?: Date | null;
}

export enum MembershipDirection {
    Members = "Members",
    Memberships = "Memberships",
    Both = "Both"
}

export interface MembershipGroupRequest {
    uri: string | null;
    members?: Array<MembershipMemberRequest>;
}

export interface MembershipMemberRequest {
    uri: string | null;
    membershipType?: MembershipPrivilegeType;
}

export enum MembershipPrivilegeType {
    Unassigned = "Unassigned",
    Standard = "Standard",
    ProxyRead = "ProxyRead",
    ProxyWrite = "ProxyWrite"
}

export interface MembershipRequest {
    groups: Array<MembershipGroupRequest>;
}

export interface MembershipResponse {
    memberships?: Array<GroupMemberRef>;
    groups?: Array<GroupRef>;
}

export interface PermissionRequest {
    uri: string | null;
    globalPermitSelf?: PrivilegeMask;
    authorizedProhibit?: PrivilegeMask;
    ownerProhibit?: PrivilegeMask;
}

export interface PermissionResponse {
    username?: string | null;
    uri?: string | null;
    collectionType?: CollectionType;
    collectionSubType?: CollectionSubType;
    principalType?: PrincipalType;
    permissions?: PrivilegeMask;
    globalPermitSelf?: PrivilegeMask;
    authorizedProhibit?: PrivilegeMask;
    ownerProhibit?: PrivilegeMask;
    isRoot?: boolean | null;
    isAdmin?: boolean | null;
}

export interface PrincipalResponse {
    username?: string | null;
    uri?: string | null;
    principalType?: PrincipalType;
    email?: string | null;
    isEmailVerified?: boolean;
    displayName?: string | null;
    timezone?: string | null;
    description?: string | null;
    dateFormatType?: string | null;
    locale?: string | null;
    color?: string | null;
    orderBy?: number | null;
    isRoot?: boolean;
    hasGroups?: boolean | null;
    hasScheduling?: boolean | null;
    permissions?: PrivilegeMask;
    globalPermitSelf?: PrivilegeMask;
    authorizedProhibit?: PrivilegeMask;
    ownerProhibit?: PrivilegeMask;
    created?: Date;
    modified?: Date;
}

export interface PrincipalType {
    id?: number;
    name?: string | null;
    label?: string | null;
}

export interface PrivilegeGroupRequest {
    code: string | null;
    principals?: Array<PrivilegePrincipalRequest>;
}

export interface PrivilegeGroupResponse {
    name: string | null;
    code: string | null;
    privileges?: Array<PrivilegeLineResponse>;
}

export interface PrivilegeItemResponse {
    id?: string | null;
    description?: string | null;
}

export interface PrivilegeLineResponse {
    uri?: string | null;
    username?: string | null;
    displayname?: string | null;
    principalType?: string | null;
    grants?: Array<PrivilegeItemResponse>;
    isIndirect?: boolean | null;
    isInherited?: boolean | null;
    isVirtual?: boolean | null;
}

export enum PrivilegeMask {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _4 = 4,
    _8 = 8,
    _16 = 16,
    _32 = 32,
    _64 = 64,
    _128 = 128,
    _198 = 198,
    _256 = 256,
    _512 = 512,
    _1024 = 1024,
    _2048 = 2048,
    _4096 = 4096,
    _7168 = 7168,
    _8192 = 8192,
    _16384 = 16384,
    _32768 = 32768,
    _57344 = 57344,
    _65535 = 65535
}

export interface PrivilegePrincipalRequest {
    username: string | null;
    doRemove?: boolean;
}

export interface PrivilegeRequest {
    grantorUri: string | null;
    groups: Array<PrivilegeGroupRequest>;
}

export interface PrivilegeResponse {
    grantedTo?: boolean;
    privilegeGroups?: Array<PrivilegeGroupResponse>;
    hasProxyWriteCollection?: boolean | null;
    hasProxyReadCollection?: boolean | null;
}

export interface ProblemDetails {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
}

export enum RelationshipTypes {
    None = "None",
    Custom = "Custom",
    Administers = "Administers",
    ReadWrite = "ReadWrite",
    Read = "Read",
    Freebusy = "Freebusy"
}

export interface SyncTokenResponse {
    token?: string | null;
}

export interface UserAmendRequest {
    displayName?: string | null;
    email?: string | null;
    isEmailVerified?: boolean;
    dateFormatType?: string | null;
    locale?: string | null;
    timezone?: string | null;
    color?: string | null;
    description?: string | null;
    isActive?: boolean;
}

export interface UserConfirmEmailRequest {
    confirmationToken: string | null;
}

export interface UserCredentialRequest {
    credentialType?: string | null;
    template?: string | null;
    username?: string | null;
    password?: string | null;
}

export enum UserRegisterCollections {
    Default = "Default",
    Calendar = "Calendar",
    Address = "Address",
    Proxy = "Proxy",
    Scheduling = "Scheduling",
    WebPush = "WebPush"
}

export interface UserRegisterRequest {
    displayName?: string | null;
    email?: string | null;
    isEmailVerified?: boolean;
    dateFormatType?: string | null;
    locale?: string | null;
    timezone?: string | null;
    color?: string | null;
    description?: string | null;
    isActive?: boolean;
    username: string | null;
    password?: string | null;
    type: string | null;
    skipCollections?: Array<UserRegisterCollections>;
}

export interface UsrCredentialType {
    id?: number;
    name?: string | null;
    label?: string | null;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
